[package]
description = "Parser for the TLS protocol"
license = "MIT/Apache-2.0"
keywords = ["TLS","SSL","protocol","parser","nom"]
homepage = "https://github.com/rusticata/tls-parser"
repository = "https://github.com/rusticata/tls-parser.git"
documentation = "https://docs.rs/tls-parser"
name = "tls-parser"
version = "0.9.4"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
categories = ["network-programming", "parser-implementations"]
edition = "2018"

readme = "README.md"
build = "build.rs"

include = [
  "LICENSE-*",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "benches/*.rs",
  "build.rs",
  "src/*.rs",
  "tests/*.rs",
  "scripts/tls-ciphersuites.txt",
  "scripts/extract-iana-ciphers.py"
]

[lib]
name = "tls_parser"

[features]
default = []
serialize = ["cookie-factory"]

[dependencies]
nom = "5.0"
phf = "0.8"
enum_primitive = "^0.1"
rusticata-macros = "2.0"
cookie-factory = { version="0.3", optional=true }

[dev-dependencies]
pretty_assertions = "0.6"

[build-dependencies]
phf_codegen = "0.8"

[badges]
travis-ci = { repository = "rusticata/tls-parser" }
